"""Initial migration

Revision ID: initial
Revises: 
Create Date: 2024-07-03 21:01:26.614694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('Apellido', sa.String(length=50), nullable=False),
    sa.Column('CorreoElectronico', sa.String(length=100), nullable=False),
    sa.Column('Telefono', sa.String(length=15), nullable=True),
    sa.Column('ImagenPerfil', sa.String(length=255), nullable=True),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('defaultBoardId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UsuarioID'),
    sa.UniqueConstraint('CorreoElectronico')
    )

    op.create_table('Boards',
    sa.Column('BoardID', sa.Integer(), nullable=False),
    sa.Column('UsuarioPropietarioID', sa.Integer(), nullable=False),
    sa.Column('Titulo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('BoardID')
    )

    op.create_table('Etiquetas',
    sa.Column('EtiquetaID', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('EtiquetaID')
    )

    op.create_table('AuditLogs',
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=True),
    sa.Column('Accion', sa.String(length=100), nullable=False),
    sa.Column('Detalles', sa.Text(), nullable=True),
    sa.Column('Fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('LogID')
    )

    op.create_table('Invitaciones',
    sa.Column('InvitacionID', sa.Integer(), nullable=False),
    sa.Column('UsuarioOrigenID', sa.Integer(), nullable=False),
    sa.Column('UsuarioDestinoID', sa.Integer(), nullable=False),
    sa.Column('Estado', sa.Enum('pendiente', 'aceptada', 'rechazada'), nullable=True),
    sa.Column('FechaEnvio', sa.DateTime(), nullable=True),
    sa.Column('FechaAceptacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('InvitacionID')
    )

    op.create_table('Notificaciones',
    sa.Column('NotificacionID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=True),
    sa.Column('Mensaje', sa.String(length=255), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=True),
    sa.Column('Leida', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('NotificacionID')
    )

    op.create_table('PerfilesUsuario',
    sa.Column('PerfilID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('Editable', sa.Boolean(), nullable=True),
    sa.Column('Biografia', sa.Text(), nullable=True),
    sa.Column('Intereses', sa.Text(), nullable=True),
    sa.Column('Ocupacion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('PerfilID')
    )

    op.create_table('Proyectos',
    sa.Column('ProyectoID', sa.Integer(), nullable=False),
    sa.Column('BoardID', sa.Integer(), nullable=False),
    sa.Column('Titulo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ProyectoID')
    )

    op.create_table('Columnas',
    sa.Column('ColumnaID', sa.Integer(), nullable=False),
    sa.Column('ColumnaNombre', sa.String(length=100), nullable=False),
    sa.Column('ProyectoID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ColumnaID')
    )

    op.create_table('Tareas',
    sa.Column('TareaID', sa.Integer(), nullable=False),
    sa.Column('ProyectoID', sa.Integer(), nullable=False),
    sa.Column('Titulo', sa.String(length=100), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.Column('Importancia', sa.Integer(), nullable=True),
    sa.Column('Estado', sa.Enum('pendiente', 'en_proceso', 'completada'), nullable=True),
    sa.Column('FechaVencimiento', sa.Date(), nullable=True),
    sa.Column('FechaCreacion', sa.DateTime(), nullable=True),
    sa.Column('UltimaActualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('TareaID')
    )

    op.create_table('Adjuntos',
    sa.Column('AdjuntoID', sa.Integer(), nullable=False),
    sa.Column('TareaID', sa.Integer(), nullable=True),
    sa.Column('Archivo', sa.String(length=255), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('AdjuntoID')
    )

    op.create_table('AsignacionesTareas',
    sa.Column('AsignacionID', sa.Integer(), nullable=False),
    sa.Column('TareaID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('AsignacionID')
    )

    op.create_table('Comentarios',
    sa.Column('ComentarioID', sa.Integer(), nullable=False),
    sa.Column('TareaID', sa.Integer(), nullable=True),
    sa.Column('UsuarioID', sa.Integer(), nullable=True),
    sa.Column('Texto', sa.Text(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ComentarioID')
    )

    op.create_table('Portadas',
    sa.Column('PortadaID', sa.Integer(), nullable=False),
    sa.Column('TareaID', sa.Integer(), nullable=True),
    sa.Column('Imagen', sa.String(length=255), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PortadaID')
    )

    op.create_table('Tareas_Columnas',
    sa.Column('TareaID', sa.Integer(), nullable=False),
    sa.Column('ColumnaID', sa.Integer(), nullable=False),
    sa.Column('Posicion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('TareaID', 'ColumnaID')
    )

    op.create_table('Tareas_Etiquetas',
    sa.Column('TareaID', sa.Integer(), nullable=False),
    sa.Column('EtiquetaID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('TareaID', 'EtiquetaID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tareas_Etiquetas')
    op.drop_table('Tareas_Columnas')
    op.drop_table('Portadas')
    op.drop_table('Comentarios')
    op.drop_table('AsignacionesTareas')
    op.drop_table('Adjuntos')
    op.drop_table('Tareas')
    op.drop_table('Columnas')
    op.drop_table('Proyectos')
    op.drop_table('PerfilesUsuario')
    op.drop_table('Notificaciones')
    op.drop_table('Invitaciones')
    op.drop_table('AuditLogs')
    op.drop_table('Usuarios')
    op.drop_table('Etiquetas')
    op.drop_table('Boards')
    # ### end Alembic commands ###
