"""Add foreign keys

Revision ID: add_foreign_keys
Revises: initial
Create Date: 2024-07-03 21:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_foreign_keys'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Boards', 'Usuarios', ['UsuarioPropietarioID'], ['UsuarioID'])
    op.create_foreign_key(None, 'Usuarios', 'Boards', ['defaultBoardId'], ['BoardID'])
    op.create_foreign_key(None, 'AuditLogs', 'Usuarios', ['UsuarioID'], ['UsuarioID'])
    op.create_foreign_key(None, 'Invitaciones', 'Usuarios', ['UsuarioOrigenID'], ['UsuarioID'])
    op.create_foreign_key(None, 'Invitaciones', 'Usuarios', ['UsuarioDestinoID'], ['UsuarioID'])
    op.create_foreign_key(None, 'Notificaciones', 'Usuarios', ['UsuarioID'], ['UsuarioID'])
    op.create_foreign_key(None, 'PerfilesUsuario', 'Usuarios', ['UsuarioID'], ['UsuarioID'])
    op.create_foreign_key(None, 'Proyectos', 'Boards', ['BoardID'], ['BoardID'])
    op.create_foreign_key(None, 'Columnas', 'Proyectos', ['ProyectoID'], ['ProyectoID'])
    op.create_foreign_key(None, 'Tareas', 'Proyectos', ['ProyectoID'], ['ProyectoID'])
    op.create_foreign_key(None, 'Adjuntos', 'Tareas', ['TareaID'], ['TareaID'])
    op.create_foreign_key(None, 'AsignacionesTareas', 'Tareas', ['TareaID'], ['TareaID'])
    op.create_foreign_key(None, 'AsignacionesTareas', 'Usuarios', ['UsuarioID'], ['UsuarioID'])
    op.create_foreign_key(None, 'Comentarios', 'Tareas', ['TareaID'], ['TareaID'])
    op.create_foreign_key(None, 'Comentarios', 'Usuarios', ['UsuarioID'], ['UsuarioID'])
    op.create_foreign_key(None, 'Portadas', 'Tareas', ['TareaID'], ['TareaID'])
    op.create_foreign_key(None, 'Tareas_Columnas', 'Columnas', ['ColumnaID'], ['ColumnaID'])
    op.create_foreign_key(None, 'Tareas_Columnas', 'Tareas', ['TareaID'], ['TareaID'])
    op.create_foreign_key(None, 'Tareas_Etiquetas', 'Etiquetas', ['EtiquetaID'], ['EtiquetaID'])
    op.create_foreign_key(None, 'Tareas_Etiquetas', 'Tareas', ['TareaID'], ['TareaID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tareas_Etiquetas', type_='foreignkey')
    op.drop_constraint(None, 'Tareas_Etiquetas', type_='foreignkey')
    op.drop_constraint(None, 'Tareas_Columnas', type_='foreignkey')
    op.drop_constraint(None, 'Tareas_Columnas', type_='foreignkey')
    op.drop_constraint(None, 'Portadas', type_='foreignkey')
    op.drop_constraint(None, 'Comentarios', type_='foreignkey')
    op.drop_constraint(None, 'Comentarios', type_='foreignkey')
    op.drop_constraint(None, 'AsignacionesTareas', type_='foreignkey')
    op.drop_constraint(None, 'AsignacionesTareas', type_='foreignkey')
    op.drop_constraint(None, 'Adjuntos', type_='foreignkey')
    op.drop_constraint(None, 'Tareas', type_='foreignkey')
    op.drop_constraint(None, 'Columnas', type_='foreignkey')
    op.drop_constraint(None, 'Proyectos', type_='foreignkey')
    op.drop_constraint(None, 'PerfilesUsuario', type_='foreignkey')
    op.drop_constraint(None, 'Notificaciones', type_='foreignkey')
    op.drop_constraint(None, 'Invitaciones', type_='foreignkey')
    op.drop_constraint(None, 'Invitaciones', type_='foreignkey')
    op.drop_constraint(None, 'AuditLogs', type_='foreignkey')
    op.drop_constraint(None, 'Usuarios', type_='foreignkey')
    op.drop_constraint(None, 'Boards', type_='foreignkey')
    # ### end Alembic commands ###
